name: receipt_manager
description: Receipt Manager 2

version: 1.1.4+360

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_clean_architecture: ^5.0.0
  injectable: ^1.2.2
  http: ^0.13.1
  camera: ^0.8.1
  path_provider: ^2.0.1
  path: ^1.8.0
  curved_navigation_bar: ^0.4.0-nullsafety.0
  shared_preferences: ^2.0.0-nullsafety.1

  equatable: ^2.0.0
  flutter_slidable: ^0.5.7
  cupertino_icons: ^1.0.0
  settings_ui: ^1.0.0-nullsafety.2
  permission_handler: ^6.1.1

  hive: ^2.0.2
  hive_flutter: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^1.0.1
  build_runner: ^1.12.2

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
