name: receipt_manager
description: Receipt Manager

version: 1.1.4+360

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_clean_architecture: ^5.0.0
  injectable: ^1.2.2
  http: ^0.13.1
  camera: ^0.8.1
  path_provider: ^2.0.1
  path: ^1.8.0

  equatable: ^2.0.0
  flutter_slidable: ^0.6.0
  cupertino_icons: ^1.0.0
  settings_ui: ^1.0.0-nullsafety.2
  permission_handler: ^6.1.1

  hive: ^2.0.2
  hive_flutter: ^1.0.0
  flutter_staggered_animations: ^1.0.0
  currency_picker: ^2.0.3
  intl: ^0.17.0
  flutter_neumorphic: ^3.0.3
  flutter_native_splash: ^1.1.7+1
  flutter_multi_formatter: ^2.0.2

  flutter_bloc: ^7.0.0-nullsafety.2
  moor_flutter: ^4.0.0
  moor_db_viewer: ^3.0.0
  animated_stack: ^0.2.0
  syncfusion_flutter_charts: ^18.4.49

  simple_edge_detection:
    path: ./flutter-simple-edge-detection

  image_picker: ^0.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: any
  moor_generator: any

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
