name: receipt_manager
description: Receipt Manager

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: '1.1.1' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.1+150

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  test:

  http: 0.12.0+4
  flutter:
    sdk: flutter
  flutter_localizations: # added
    sdk: flutter

  camera: ^0.5.8+9
  path_provider:
  path:
  curved_navigation_bar: ^0.3.4
  shared_preferences:  ^0.5.12+2
  giffy_dialog: ^1.8.0
  flutter_bloc: ^6.0.6
  equatable: ^1.2.5
  moor_flutter: ^3.1.0
  flutter_slidable: ^0.5.7
  moor: ^3.3.1
  cupertino_icons: ^1.0.0
  intl:
  settings_ui: ^0.4.0
  flutter_staggered_grid_view: ^0.3.2
  permission_handler: ^5.0.1+1
  fl_chart: ^0.12.0
  image: ^2.1.18
  progress_dialog: ^1.2.4
  rounded_loading_button: ^1.0.0
  simple_autocomplete_formfield: ^0.2.7
  flutter_onboard: ^0.1.0
  provider: ^4.3.2+2
  random_color: ^1.0.5
  simple_animations: ^2.2.2
  random_date: ^0.0.5
  flutter_svg: ^0.19.0
  percent_indicator: ^2.1.1
  toggle_switch: "^0.1.8"
  flutter_staggered_animations: "^0.1.2"
  bonsoir: ^0.1.3+2
  device_info: ^2.0.0
  pull_to_refresh: ^1.4.5
  syncfusion_flutter_charts: ^18.4.48

flutter_localizations:
  sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator:
  build_runner:
  intl_translation:
    git:
      url: https://github.com/nt4f04uNd/intl_translation

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec


# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/

flutter_intl:
  main_locale: de_DE
  enabled: true
