name: receipt_manager2
description: Receipt Manager 2

version: 1.1.4+360

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_clean_architecture: ^5.0.0
  injectable: ^1.2.2
  http: ^0.12.0+2
  cupertino_icons: ^0.1.2


flutter_localizations:
  sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_intl:
  main_locale: de_DE
  enabled: true
