name: receipt_manager
description: Receipt Manager

version: 1.1.6+605

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_card_swipper: ^0.4.0
  flutter_clean_architecture: ^5.0.0
  injectable: ^1.2.2
  http: ^0.13.1
  path_provider: ^2.0.1
  path: ^1.8.0

  equatable: ^2.0.0
  flutter_slidable: ^0.6.0
  cupertino_icons: ^1.0.0
  settings_ui: ^1.0.0-nullsafety.2
  permission_handler: ^7.1.0

  hive: ^2.0.2
  hive_flutter: ^1.0.0
  flutter_staggered_animations: ^1.0.0
  currency_picker: ^2.0.3
  intl: ^0.17.0
  flutter_neumorphic: ^3.1.0
  flutter_multi_formatter: ^2.0.2

  flutter_bloc: ^7.0.0-nullsafety.2
  moor_flutter: ^4.0.0
  animated_stack: ^0.2.0
  syncfusion_flutter_charts: ^19.1.58

  image_picker: ^0.7.4
  flutter_typeahead: ^3.1.1
  file_picker: ^3.0.1

  flutter_uploader: any
  flutter_local_notifications: any
  gallery_saver: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: any
  moor_generator: any

  flutter_native_splash: ^1.1.7+1

  # Localisation
  flutter_localizations:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.png
  color_dark: "#ffffff"
  fullscreen: true

flutter_intl:
  enabled: true